[package]
name = "risp"
version = "0.1.0"
authors = ["Gustavo <nowayhecodes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
rustyline = "7.1.0"